### ISSUE TITLE
3D items when I drop items when dropped items is on fast

### ISSUE THREAD

**Issue by vinnyg0621** [JackDotJS/OptiFine#6]
when I applied the dropped items to fast, the items were still 3d.
![2020-08-14_18 54 09](https://user-images.githubusercontent.com/57818441/90303097-06c4aa00-de60-11ea-8e02-f0b76c6b6ef5.png)
![2020-08-14_18 54 28](https://user-images.githubusercontent.com/57818441/90303098-09270400-de60-11ea-804e-5cd45488680e.png)

**Comment by JackDotJS** [comment]
This is not the OptiFine issue tracker. Go here: https://github.com/sp614x/optifine/issues
